### ISSUE TITLE
Did I do something wrong?

### ISSUE THREAD

**Issue by nguyenvancaokys** [jaymoulin/yamete#13]
I used the following code
`docker run --rm -ti -v path/to/download jaymoulin/yamete download -u https://domain.com/album`

Error
```
C:\Program Files\Docker Toolbox\docker.exe: error during connect: Post http://%2F%2F.%2Fpipe%2Fdocker_engine/v1.36/containers/create: open //./pipe/docker_engine: The system cannot find the file specified. In the default daemon configuration on Windows, the docker client must be run elevated to connect. This error may also indicate that the docker daemon is not running.
See 'C:\Program Files\Docker Toolbox\docker.exe run --help'.
```

**Comment by jaymoulin** [comment]
Please insert the real command you typed so I can help. It looks like you have not entered a correct path for your downloads (volume is not mounted). Also, it seems you cannot connect to docker, so your installation might be incomplete/corrupted. Please try this command to check that the problem comes from your installation/rights : `docker run hello-world`
