### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by smhmd** [jaymoulin/yamete#19]
Non-PHP developer here. Installation instructions without Docker are missed.

I'm on an Arch Linux machine. I installed `php (7.3.11)` and `composer (1.9.1)`, and ran `$ composer global require jaymoulin/yamete`, which gave me these errors:
```postcss
Using version ^1.8 for jaymoulin/yamete
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - jaymoulin/yamete 1.8.0 requires jaymoulin/guzzlehttp-cloudflare ^1.0.0 -> satisfiable by jaymoulin/guzzlehttp-cloudflare[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - jaymoulin/yamete 1.8.1 requires jaymoulin/guzzlehttp-cloudflare ^1.0.0 -> satisfiable by jaymoulin/guzzlehttp-cloudflare[1.0.0, 1.0.1, 1.0.2, 1.0.3].
    - jaymoulin/guzzlehttp-cloudflare 1.0.0 requires kyranrana/cloudflare-bypass ^v3.0 -> satisfiable by kyranrana/cloudflare-bypass[3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.3.0].
    - jaymoulin/guzzlehttp-cloudflare 1.0.1 requires kyranrana/cloudflare-bypass ^v3.0 -> satisfiable by kyranrana/cloudflare-bypass[3.0.0, 3.1.0, 3.1.1, 3.1.2, 3.1.3, 3.2.0, 3.2.1, 3.3.0].
    - kyranrana/cloudflare-bypass 3.3.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - kyranrana/cloudflare-bypass 3.2.1 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - kyranrana/cloudflare-bypass 3.2.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - kyranrana/cloudflare-bypass 3.1.3 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - kyranrana/cloudflare-bypass 3.1.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - kyranrana/cloudflare-bypass 3.1.1 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - kyranrana/cloudflare-bypass 3.1.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - kyranrana/cloudflare-bypass 3.0.0 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - jaymoulin/guzzlehttp-cloudflare 1.0.3 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - jaymoulin/guzzlehttp-cloudflare 1.0.2 requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.
    - Installation request for jaymoulin/yamete ^1.8 -> satisfiable by jaymoulin/yamete[1.8.0, 1.8.1].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php/php.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, deleting ./composer.json.

```

I googled a bit. and people advice to install packages (e.g. `php-xsl`) that will solve whatever OP's errors were. so, I'm kinda on my own.

**Comment by smhmd** [comment]
I installed Docker instead.

**Comment by jaymoulin** [comment]
Thank you for your issue.

If you find this product useful, don't forget to support me by donating (support button or badges on top on the README). You cann support by watching ads on https://utip.io/femtopixel.

For other users or further information, the error message reported clearly states that the extension `bcmath` is required and still missing. It can be installed with a command like `sudo apt-get install php-bcmath`

**Comment by smhmd** [comment]
> [in Arch], It's [php-bcmath] built in to the php package, you just need to enable it in your php config.

Any idea how to do that?

---
I personally would not mind learning Docker/light PHP package management to get up and running with `yamete`. But, you would probably have more reach if you offered packages or more detailed instructions. I pulled the Docker image successfully, but no idea where to go from there, for instance.

**Comment by jaymoulin** [comment]
I provided a Docker image to offer a ready-to-use package, so that you have nothing but the one-liner to use (https://github.com/jaymoulin/yamete#docker).

Depending on you OS (Debian based I would assume but you didn't specify it in the issue despite to the issue formatting template), the extensions can be installed with `sudo apt-get install php-bcmath`. For Arch system, you have to compile everything. As Alpine is similar at some point to arch systems, you could find all the requirements in https://github.com/jaymoulin/yamete/blob/master/docker/Dockerfile
I do not know how MacOs or Windows systems handle this.

The PHP package exists so developers can use it in their own projects.

There is already documentation for the already known product such as PHP, Composer or Docker and I have no value to offer for this.

External references:
- PHP : https://www.php.net/manual/en/tutorial.php & https://www.php.net/manual/en/install.php
- Composer : https://getcomposer.org/doc/00-intro.md
- Docker : https://www.docker.com/resources/what-container

I hope all your questions are now clarified.
