### ISSUE TITLE
myhentaigallery.com downloads stopped working

### ISSUE THREAD

**Issue by Uriei** [jaymoulin/yamete#29]
**Output of `docker inspect jaymoulin/yamete --format='{{index .Config.Labels.version}}'`:**

```
1.13.0
```

**Description**
When trying to download any album from myhentaigallery.com I get "No result on download url"

**Steps to reproduce the issue:**
1. Try to download anything from myhentaigallery.com
2. Fail
3. Cry

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/6078221/89730129-47758b00-da3c-11ea-9382-d01cd3efd60c.png)

**Describe the results you expected:**
Getting some sweet stuff

**Additional information you deem important (e.g. issue happens only occasionally):**
My batchfile is basically this.
```
docker pull jaymoulin/yamete
docker run --rm -ti -v D:/Uri/X/yamete:/app/downloads jaymoulin/yamete download -vv -n -e /app/downloads/error.txt -l /app/downloads/galleries.txt
```

**Comment by jaymoulin** [comment]
Thank you for reporting this. If you like this product, please consider donation to help me continue maintain and create great products ([![PayPal donation](https://github.com/jaymoulin/jaymoulin.github.io/raw/master/ppl.png "PayPal donation")](https://www.paypal.me/jaymoulin) [![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png "Buy me a coffee")](https://www.buymeacoffee.com/3Yu8ajd7W) [![Become a Patron](https://badgen.net/badge/become/a%20patron/F96854 "Become a Patron")](https://patreon.com/jaymoulin))

This driver has already been fixed in the 1.16.0 July release, available for Patreon users. You can download it by supporting me on Patreon.
